[0m21:05:49.908687 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F42CC6010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F42CC6E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F42CC4C90>]}


============================== 21:05:49.913293 | cb098889-0651-4465-9c2b-971d7b6e68c4 ==============================
[0m21:05:49.913293 [info ] [MainThread]: Running with dbt=1.7.4
[0m21:05:49.914319 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\MSI Modern 14\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init warehouse', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:05:49.917612 [debug] [MainThread]: Starter project path: D:\Data_Engineer\Project_DE\ETL-ELT\data_pipeline_basic\pipe_env\Lib\site-packages\dbt\include\starter_project
[0m21:05:49.962927 [info ] [MainThread]: 
Your new dbt project "warehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:05:49.963930 [info ] [MainThread]: Setting up your profile.
[0m21:08:14.319485 [info ] [MainThread]: Profile warehouse written to C:\Users\MSI Modern 14\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:08:14.321479 [debug] [MainThread]: Command `dbt init` succeeded at 21:08:14.321479 after 144.48 seconds
[0m21:08:14.322464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F42CB05D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F42CB35D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025F42CBE850>]}
[0m21:08:14.322464 [debug] [MainThread]: Flushing usage events
[0m21:08:24.907085 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198B6AFD450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198B6E17090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198B6B268D0>]}


============================== 21:08:24.912352 | 485fa230-fb6c-45d5-a51e-44430eec3422 ==============================
[0m21:08:24.912352 [info ] [MainThread]: Running with dbt=1.7.4
[0m21:08:24.912818 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\MSI Modern 14\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:08:24.913863 [info ] [MainThread]: dbt version: 1.7.4
[0m21:08:24.914851 [info ] [MainThread]: python version: 3.11.5
[0m21:08:24.914851 [info ] [MainThread]: python path: D:\Data_Engineer\Project_DE\ETL-ELT\data_pipeline_basic\pipe_env\Scripts\python.exe
[0m21:08:24.914851 [info ] [MainThread]: os info: Windows-10-10.0.22621-SP0
[0m21:08:24.920632 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m21:08:25.011500 [info ] [MainThread]: Using profiles dir at C:\Users\MSI Modern 14\.dbt
[0m21:08:25.013493 [info ] [MainThread]: Using profiles.yml file at C:\Users\MSI Modern 14\.dbt\profiles.yml
[0m21:08:25.014516 [info ] [MainThread]: Using dbt_project.yml file at D:\Data_Engineer\Project_DE\ETL-ELT\data_pipeline_basic\dbt_project.yml
[0m21:08:25.015559 [info ] [MainThread]: Configuration:
[0m21:08:25.015736 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m21:08:25.016593 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m21:08:25.016593 [info ] [MainThread]: Required dependencies:
[0m21:08:25.017955 [debug] [MainThread]: Executing "git --help"
[0m21:08:25.057999 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m21:08:25.059505 [debug] [MainThread]: STDERR: "b''"
[0m21:08:25.060676 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m21:08:25.060676 [info ] [MainThread]: Connection test skipped since no profile was found
[0m21:08:25.061691 [info ] [MainThread]: [31m2 checks failed:[0m
[0m21:08:25.062697 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "py_dbt_project", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!


[0m21:08:25.063700 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\Data_Engineer\Project_DE\ETL-ELT\data_pipeline_basic\dbt_project.yml> not found

[0m21:08:25.064700 [debug] [MainThread]: Command `dbt debug` failed at 21:08:25.063700 after 0.21 seconds
[0m21:08:25.064700 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198B7246D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198AFD902D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000198B6A56510>]}
[0m21:08:25.065700 [debug] [MainThread]: Flushing usage events
[0m17:58:52.279825 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1E9D68D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1EDC21D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1EDC1E90>]}


============================== 17:58:52.283662 | e70773e1-8634-41c3-beff-a17aeea0ad41 ==============================
[0m17:58:52.283662 [info ] [MainThread]: Running with dbt=1.7.4
[0m17:58:52.284710 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\MSI Modern 14\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt docs serve', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:58:52.285903 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Data_Engineer\Project_DE\ETL-ELT\data_pipeline_basic\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:58:52.286927 [debug] [MainThread]: Command `dbt docs serve` failed at 17:58:52.286927 after 0.06 seconds
[0m17:58:52.287926 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1EDE7250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1E8C0B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BC1E969C10>]}
[0m17:58:52.287926 [debug] [MainThread]: Flushing usage events
[0m19:08:53.227846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002711CC88B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002711C750C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002711CC51050>]}


============================== 19:08:53.231941 | 51baf16a-7455-4484-8e41-1af02e01e043 ==============================
[0m19:08:53.231941 [info ] [MainThread]: Running with dbt=1.7.4
[0m19:08:53.231941 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\MSI Modern 14\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': "dbt run-operation generate_base_model --args {'source_name': 'src_postgres', 'table_name': 'src_Sales_Customer'}", 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:08:53.231941 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Data_Engineer\Project_DE\ETL-ELT\data_pipeline_basic\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:08:53.239721 [debug] [MainThread]: Command `dbt run-operation` failed at 19:08:53.231941 after 0.06 seconds
[0m19:08:53.240225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002711C52ECD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002711C750210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002711C4AE550>]}
[0m19:08:53.240225 [debug] [MainThread]: Flushing usage events
